setwd("C:/Users/zjpla/OneDrive/Work/R/Unit 2 -Linear Regression")
Training<- read.csv("pisa2009train.csv")
Test<-read.csv("pisa2009test.csv")
str(Training)
tapply(Training$grade,Training$male,mean)
tapply(Training$readingScore,Training$male,mean)
pisaTrain=na.omit
pisaTrain=na.omit(Training)
pisaTest<-na.omit(Test)
str(pisaTrain)
summary(pisaTest)
str(pisaTest)
pisaTrain$raceeth = relevel(pisaTrain$raceeth, "White")
pisaTest$raceeth = relevel(pisaTest$raceeth, "White")
str(pisaTest)
ImScore=lm(pisaTrain$readingScore ~.,data =pisaTrain )
summary(ImScore)
lmscore<-ImScore
SSE<- sum( (lmscore$residuals)^2)
RMSE<- sqrt ( SSE/nrow(pisaTrain))
RMSE
predTest<-predict(lmscore,newdata = pisaTest)
summary(predTest)
str(predTest)
SSE=sum( (pisaTest$readingScore- predTest )^2)
SSR= sqrt(SSE/nrow(pisaTest))
SSR
baseline = mean(pisaTrain$readingScore)
baseline
savehistory("C:/Users/zjpla/Desktop/temp.r")
